name: Copilot Agent

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  run-copilot-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Copilot Agent
        uses: github/copilot-agent@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
